### ISSUE TITLE
Home Button Function

### ISSUE THREAD

**Issue by ThomasSzentirmay** [ThomasSzentirmay/weather-flix-project#2]
-When the button with id='enter-home' is clicked, make the event listener add a class to make the welcome container 'display: none' and take that class off our main home section so it can be displayed.

The class for displaying or hiding is called '.display-none'

**Comment by jp-king-1337** [comment]
The class for displaying is called display

**Comment by jp-king-1337** [comment]
Added, Thomas approved the pull request.
